### ISSUE TITLE
Kubernetes stateful set does not correctly cooperate with distributed zfs provisioners

### ISSUE THREAD

**Issue by rajha-korithrien** [rajha-korithrien/kubernetes-zfs-provisioner#13]
Consider the following statefulset definition, deployed on a cluster with 3 nodes, each node running a zfs-provisioner

```
apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: paas-zookeeper
  labels:
    app: example
spec:
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
  clusterIP: None
  selector:
    app: example
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-example
  namespace: paas-zookeeper
spec:
  serviceName: "example"
  selector:
    matchLabels:
      app: stateful-example
  replicas: 3
  template:
    metadata:
      labels:
        app: stateful-example
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - stateful-example
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: stateful-example
        image: busybox
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "sleep 10; if [ -e /mnt/SUCCESS ]; then echo 'file already exists'; ls -la /mnt; exit 0; else echo 'file does not exist attempting to create it'; id && touch /mnt/SUCCESS && exit 0 || exit 1; fi"
        volumeMounts:
        - name: zfs-volume
          mountPath: "/mnt"
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: zfs-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1M
      storageClassName: zfs-mirror
```
When deployed with a correctly configured storageClass (to cause kuberentes to use a zfs-provisioner) and configMap (so the 3 provisioners work together to balance the provision requests), everything from the persistent volume claim side works as expected. The provisioners work together and one persistent volume claim gets created per node in the cluster.

```
kubectl --namespace paas-zookeeper get pvc
NAME                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
zfs-volume-stateful-example-0   Bound    pvc-12bb0357-4102-11e9-9844-e0db5570db3f   1M         RWO            zfs-mirror     3h
zfs-volume-stateful-example-1   Bound    pvc-202e6a2a-4102-11e9-9844-e0db5570db3f   1M         RWO            zfs-mirror     3h
zfs-volume-stateful-example-2   Bound    pvc-2b3118a9-4102-11e9-9844-e0db5570db3f   1M         RWO            zfs-mirror     3h
```

Notice from the stateful set definition that /mnt/SUCCESS should exist in the provisioned volume, made apparent by the container running an ls. However this is not always observed. For some pods it works as expected (after the statefulset controller redeploys a the first instance of the pod the logs show):
```
 kubectl --namespace paas-zookeeper logs stateful-example-1
file already exists
total 3
drw-rwxr--    2 root     1000             3 Mar  7 17:55 .
drwxr-xr-x   13 root     root            14 Mar  7 21:00 ..
-rw-r--r--    1 1000     root             0 Mar  7 17:55 SUCCESS
```
For other pods we see the following:
```
kubectl --namespace paas-zookeeper logs stateful-example-2
file does not exist attempting to create it
uid=1000 gid=0(root) groups=1000
touch: /mnt/SUCCESS: Permission denied
```
We can manually verify on each host that the zfs dataset has been correctly mounted and has correct permissions (the provisioner created/mounted the dataset and then did a chgrp/chmod) but for some reason kubernetes did not correctly bind mount the host zfs mount point into the container. Indeed on hosts with pods that are unable to touch /mnt/SUCCESS we see "ghost" pvc directories next to the correctly created/mounted ZFS dataset mount.
```
#zfs-list
kubernetes-mirror/pvc/pvc-12bb0357-4102-11e9-9844-e0db5570db3f                       977K   953K    24K  /mnt/kubernetes-mirror/pvc/pvc-12bb0357-4102-11e9-9844-e0db5570db3f
# pwd
/mnt/kubernetes-mirror/pvc
[root@argus-a-p pvc]# ls -la
total 2
drwxr-xr-x    4 root     root             4 Mar  7 18:08 .
drwxr-xr-x    3 root     root             3 Jan 24 00:29 ..
drw-rwxr--    2 root     input            2 Mar  7 17:54 pvc-12bb0357-4102-11e9-9844-e0db5570db3f
drwxr-xr-x    2 root     root             2 Mar  7 18:08 pvc-2b3118a9-4102-11e9-9844-e0db5570db3f
#
```
In the above the host has a correctly created/mounted zfs dataset named pvc-12bb0357-4102-11e9-9844-e0db5570db3f but is also has a directory named after a dataset created on a different host. The zfs-provisioner didn't put this other directory there, so kubernetes must have created it.
